#!/usr/bin/env python3
"""
GNSS Stack Manager
==================
Manages the three-layer GNSS data pipeline:

  Layer 1 – ser2net:
    Serial port → TCP server (raw NMEA + RTCM3)
    Optional; configurable via [ser2net] in the TOML.

  Layer 2 – str2str (RTKLIB):
    TCP client (→ ser2net) → RTCM3 filter → multiple outputs

  Layer 3 – Web frontend (app.py):
    Runs as an independent service, completely decoupled from this manager.

Modes:
    --generate-yaml   Generate the ser2net YAML only, then exit.
                      Called as ExecStartPre in the systemd unit.
                      A non-zero exit code prevents ExecStart from running.

    (no flag)         Normal start: manage ser2net + str2str as subprocesses.
                      Called as ExecStart.
"""

import argparse
import logging
import os
import signal
import subprocess
import sys
import textwrap
import threading
import time
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
# TOML
# ──────────────────────────────────────────────────────────────────────────────
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        print("ERROR: No TOML parser available. Python<3.11: pip install tomli",
              file=sys.stderr)
        sys.exit(1)


# ──────────────────────────────────────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────────────────────────────────────
def setup_logging(log_file: str, level: str) -> logging.Logger:
    logger = logging.getLogger("gnss_manager")
    logger.setLevel(getattr(logging, level.upper(), logging.INFO))
    fmt = logging.Formatter(
        "%(asctime)s [%(levelname)-8s] %(name)s: %(message)s",
        "%Y-%m-%d %H:%M:%S")
    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(fmt)
    logger.addHandler(ch)
    if log_file:
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        fh = logging.FileHandler(log_file)
        fh.setFormatter(fmt)
        logger.addHandler(fh)
    return logger


# ──────────────────────────────────────────────────────────────────────────────
# ser2net YAML Generator
# ──────────────────────────────────────────────────────────────────────────────
def generate_ser2net_yaml(cfg: dict) -> str:
    """Generates a ser2net v4+ YAML configuration as a string."""
    device    = cfg.get("device",          "/dev/ttyUSB0")
    baudrate  = cfg.get("baudrate",        115200)
    port      = cfg.get("port",            4001)
    bind_addr = cfg.get("bind_addr",       "127.0.0.1")
    max_conn  = cfg.get("max_connections", 10)
    timeout   = cfg.get("timeout",         0)

    # Options with fixed indentation (4 spaces) – no textwrap.dedent,
    # as that would strip the indentation of the interpolated variable and
    # break the YAML structure (max-connections would end up at column 0).
    opts = "    kickolduser: false\n"
    if max_conn > 0:
        opts += f"    max-connections: {max_conn}\n"
    if timeout > 0:
        opts += f"    timeout: {timeout}\n"

    lines = [
        "%YAML 1.1",
        "---",
        "# Auto-generated by GNSS Stack Manager",
        f"# Source : {device} @ {baudrate} baud",
        f"# TCP    : {bind_addr}:{port}",
        "#",
        "# DO NOT edit manually – regenerated from /etc/gnss/str2str.toml",
        "# on every start of gnss-stack.",
        "",
        "connection: &gnss",
        f"  accepter: tcp,{bind_addr},{port}",
        "  enable: on",
        "  options:",
        opts.rstrip(),
        f"  connector: serialdev,{device},{baudrate}N81,local",
        "",
    ]
    return "\n".join(lines)


def cmd_generate_yaml(config_path: str) -> int:
    """
    Reads [ser2net] from the TOML and writes the ser2net YAML file.

    Return value: 0 = success, 1 = error.
    A non-zero exit code causes systemd to abort ExecStart –
    gnss-stack.service fails and is retried after RestartSec.
    The dashboard is not affected (no dependency).
    """
    # Minimal logging for ExecStartPre – goes directly to the journal
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
        stream=sys.stdout)
    log = logging.getLogger("generate-yaml")

    try:
        with open(config_path, "rb") as f:
            config = tomllib.load(f)
    except Exception as e:
        log.error("Failed to read TOML: %s", e)
        return 1

    ser2net_cfg = config.get("ser2net", {})

    if not ser2net_cfg.get("enabled", True):
        log.info("ser2net disabled (enabled=false) – no YAML generated.")
        # Not an error: ser2net simply won't be started
        return 0

    yaml_path    = ser2net_cfg.get("config_file", "/etc/gnss/ser2net.yaml")
    yaml_content = generate_ser2net_yaml(ser2net_cfg)

    try:
        p = Path(yaml_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(yaml_content)
        log.info("ser2net YAML written: %s", yaml_path)
        log.info("  Device : %s @ %s baud",
                 ser2net_cfg.get("device",    "/dev/ttyUSB0"),
                 ser2net_cfg.get("baudrate",  115200))
        log.info("  TCP    : %s:%s",
                 ser2net_cfg.get("bind_addr", "127.0.0.1"),
                 ser2net_cfg.get("port",      4001))
        return 0
    except PermissionError as e:
        log.error("No write permission on %s: %s", yaml_path, e)
        log.error("  → Check ReadWritePaths in the gnss-stack.service unit.")
        return 1
    except Exception as e:
        log.error("Error writing %s: %s", yaml_path, e)
        return 1


# ──────────────────────────────────────────────────────────────────────────────
# Managed Process  (Subprocess mit Reconnect-Loop)
# ──────────────────────────────────────────────────────────────────────────────
class ManagedProcess:
    def __init__(self, name: str, cmd: list[str], logger: logging.Logger,
                 restart_delay: int = 5, max_restarts: int = 0,
                 reconnect: bool = True):
        self.name          = name
        self.cmd           = cmd
        self.logger        = logger.getChild(name)
        self.restart_delay = restart_delay
        self.max_restarts  = max_restarts
        self.reconnect     = reconnect
        self._proc         = None
        self._running      = False
        self._restarts     = 0

    def start(self):
        self._running = True
        self._loop()

    def _loop(self):
        while self._running:
            self.logger.info("Starting: %s", " ".join(self.cmd))
            try:
                self._proc = subprocess.Popen(
                    self.cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                )
                for line in self._proc.stdout:
                    line = line.rstrip()
                    if line:
                        self.logger.debug("  > %s", line)
                self._proc.wait()
                rc = self._proc.returncode
            except FileNotFoundError:
                self.logger.error("Binary not found: %s", self.cmd[0])
                self._running = False
                return
            except Exception as exc:
                self.logger.error("Error: %s", exc)
                rc = -1

            if not self._running:
                break

            self.logger.warning("Process exited (rc=%d).", rc)

            if not self.reconnect:
                self.logger.info("reconnect=false – not restarting.")
                break

            self._restarts += 1
            if self.max_restarts > 0 and self._restarts >= self.max_restarts:
                self.logger.error("Max restarts (%d) reached.", self.max_restarts)
                break

            self.logger.info("Restarting in %ds (attempt %d)…",
                             self.restart_delay, self._restarts)
            time.sleep(self.restart_delay)

    def stop(self):
        self._running = False
        if self._proc and self._proc.poll() is None:
            self.logger.info("Terminating PID %d…", self._proc.pid)
            self._proc.terminate()
            try:
                self._proc.wait(timeout=6)
            except subprocess.TimeoutExpired:
                self._proc.kill()
                self._proc.wait()
        self.logger.info("Stopped.")

    @property
    def is_running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None


# ──────────────────────────────────────────────────────────────────────────────
# URL builder for str2str
# ──────────────────────────────────────────────────────────────────────────────
def build_str2str_input_url(inp: dict) -> str:
    t = inp.get("type", "tcpcli").lower()
    if t == "tcpcli":
        return (f"tcpcli://{inp.get('host','127.0.0.1')}"
                f":{inp.get('port',4001)}")
    elif t == "tcpsvr":
        return f"tcpsvr://:{inp.get('port',9000)}"
    elif t == "serial":
        return (f"serial://{inp.get('device','/dev/ttyUSB0')}"
                f":{inp.get('baudrate',115200)}:8:n:1:off")
    elif t == "ntrip":
        host, port = inp.get("host",""), inp.get("port",2101)
        mp   = inp.get("mountpoint","")
        user = inp.get("user","")
        pw   = inp.get("password","")
        if user:
            return f"ntrip://{user}:{pw}@{host}:{port}/{mp}"
        return f"ntrip://{host}:{port}/{mp}"
    elif t == "file":
        return f"file://{inp.get('path','/dev/stdin')}"
    else:
        raise ValueError(f"Unknown str2str input type: '{t}'")


def build_str2str_output_url(out: dict) -> str:
    t    = out.get("type", "").lower()
    bind = out.get("bind_addr", "")

    if t == "tcpsvr":
        port = out.get("port", 9001)
        addr = (f"{bind}:{port}"
                if bind and bind not in ("0.0.0.0","") else f":{port}")
        return f"tcpsvr://{addr}"
    elif t == "udpsvr":
        port = out.get("port", 9002)
        addr = (f"{bind}:{port}"
                if bind and bind not in ("0.0.0.0","") else f":{port}")
        return f"udpsvr://{addr}"
    elif t == "file":
        from datetime import datetime
        path = datetime.utcnow().strftime(out.get("path", "/tmp/rtcm3.rtcm3"))
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        return f"file://{path}"
    elif t == "ntrip":
        host, port = out.get("host",""), out.get("port",2101)
        mp   = out.get("mountpoint","")
        user = out.get("user","")
        pw   = out.get("password","")
        if user:
            return f"ntrips://{user}:{pw}@{host}:{port}/{mp}"
        return f"ntrips://{host}:{port}/{mp}"
    elif t == "ntripsvr":
        port = out.get("port", 2101)
        mp   = out.get("mountpoint","")
        user = out.get("user","")
        pw   = out.get("password","")
        if user:
            return f"ntripsvr://{user}:{pw}@:{port}/{mp}"
        return f"ntripsvr://:{port}/{mp}"
    else:
        raise ValueError(f"Unknown str2str output type: '{t}'")


def build_str2str_cmd(binary: str, input_url: str, out: dict) -> list[str]:
    output_url = build_str2str_output_url(out)
    cmd = [binary, "-in", input_url, "-out", output_url]
    msgs = out.get("rtcm_messages", "").strip()
    if msgs:
        cmd += ["-msg", msgs]
    if out.get("type") == "file":
        swap = out.get("swap_interval", 0)
        if swap > 0:
            cmd += ["-t", str(swap)]
    return cmd


# ──────────────────────────────────────────────────────────────────────────────
# Main manager
# ──────────────────────────────────────────────────────────────────────────────
class GNSSStackManager:
    def __init__(self, config_path: str):
        with open(config_path, "rb") as f:
            self.config = tomllib.load(f)

        gen = self.config.get("general", {})
        self.logger = setup_logging(
            gen.get("log_file",    "/var/log/gnss/manager.log"),
            gen.get("log_level",   "INFO"),
        )
        self.restart_delay = gen.get("restart_delay", 5)
        self.max_restarts  = gen.get("max_restarts",  0)
        self._processes: list[ManagedProcess]  = []
        self._threads:   list[threading.Thread] = []

    # ── ser2net ───────────────────────────────────────────────────────────────
    def _start_ser2net(self):
        cfg = self.config.get("ser2net", {})
        if not cfg.get("enabled", True):
            self.logger.info("ser2net disabled – skipping.")
            return

        binary    = cfg.get("binary",      "/usr/sbin/ser2net")
        yaml_path = cfg.get("config_file", "/etc/gnss/ser2net.yaml")

        # The YAML was already written by ExecStartPre (--generate-yaml).
        # If it is missing (e.g. manual start without ExecStartPre) we log
        # the error but do not abort – str2str will still be started.
        if not Path(yaml_path).exists():
            self.logger.error(
                "ser2net YAML missing: %s\n"
                "  Was ExecStartPre executed correctly? "
                "Check ReadWritePaths in the unit.", yaml_path)
            return

        bind = cfg.get("bind_addr", "127.0.0.1")
        port = cfg.get("port",      4001)
        self.logger.info("ser2net: %s @ %s → TCP %s:%d",
                         cfg.get("device"), cfg.get("baudrate"), bind, port)

        cmd = [binary, "-n", "-c", yaml_path]
        self._launch(ManagedProcess(
            name="ser2net", cmd=cmd, logger=self.logger,
            restart_delay=self.restart_delay,
            max_restarts=self.max_restarts,
            reconnect=True,
        ))
        # Give ser2net a moment to open the port before str2str connects
        time.sleep(1.5)

    # ── str2str ───────────────────────────────────────────────────────────────
    def _start_str2str(self):
        cfg_s2s = self.config.get("str2str", {})
        binary  = cfg_s2s.get("binary",  "/usr/local/bin/str2str")
        inp_cfg = cfg_s2s.get("input",   {})
        outputs = cfg_s2s.get("outputs", [])

        if not outputs:
            self.logger.warning("str2str: no [[str2str.outputs]] defined.")
            return

        try:
            input_url = build_str2str_input_url(inp_cfg)
        except ValueError as e:
            self.logger.error("str2str input URL: %s", e)
            return

        self.logger.info("str2str input: %s", input_url)

        for out in outputs:
            if not out.get("enabled", True):
                self.logger.info("str2str output '%s' disabled.",
                                 out.get("name"))
                continue
            try:
                cmd = build_str2str_cmd(binary, input_url, out)
            except ValueError as e:
                self.logger.error("str2str output '%s': %s",
                                  out.get("name"), e)
                continue

            self._launch(ManagedProcess(
                name=f"str2str.{out.get('name','out')}",
                cmd=cmd, logger=self.logger,
                restart_delay=self.restart_delay,
                max_restarts=self.max_restarts,
                reconnect=out.get("reconnect", True),
            ))
            self.logger.info("str2str %-22s → %s",
                             out.get("name"), " ".join(cmd))

    # ── Thread-Launcher ───────────────────────────────────────────────────────
    def _launch(self, proc: ManagedProcess):
        self._processes.append(proc)
        t = threading.Thread(target=proc.start, name=proc.name, daemon=True)
        self._threads.append(t)
        t.start()

    # ── Main loop ─────────────────────────────────────────────────────────────
    def start(self):
        self.logger.info("═══ GNSS Stack Manager starting ═══")
        self._start_ser2net()
        self._start_str2str()

        # Keep running even without active processes – the user can adjust
        # the config in the dashboard and restart the service. systemd should
        # not consider the manager failed just because no data source is
        # configured yet.
        if not self._threads:
            self.logger.warning(
                "No processes started "
                "(ser2net disabled / no active outputs?).\n"
                "  Manager staying active – adjust the configuration in the "
                "dashboard and run 'systemctl restart gnss-stack'.")

        self.logger.info("Manager running. %d process(es) started.",
                         len(self._processes))
        try:
            while True:
                time.sleep(5)
                alive = sum(1 for t in self._threads if t.is_alive())
                if self._threads and alive == 0:
                    self.logger.warning(
                        "All process threads have exited – manager shutting down.")
                    break
        except KeyboardInterrupt:
            self.stop()

    def stop(self):
        self.logger.info("Stopping all processes…")
        for proc in self._processes:
            proc.stop()
        self.logger.info("All processes stopped.")

    def status(self) -> list[dict]:
        return [
            {
                "name":     p.name,
                "running":  p.is_running,
                "pid":      p._proc.pid if p._proc else None,
                "restarts": p._restarts,
                "cmd":      " ".join(p.cmd),
            }
            for p in self._processes
        ]


# ──────────────────────────────────────────────────────────────────────────────
# Signal handler for systemd
# ──────────────────────────────────────────────────────────────────────────────
def _handle_signal(manager: GNSSStackManager, signum, _frame):
    logging.getLogger("gnss_manager").info("Signal %d received – shutting down.", signum)
    manager.stop()
    sys.exit(0)


# ──────────────────────────────────────────────────────────────────────────────
# Entry point
# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="GNSS Stack Manager (ser2net + str2str)")
    parser.add_argument(
        "--config", default="/etc/gnss/str2str.toml",
        help="Path to the TOML configuration file")
    parser.add_argument(
        "--generate-yaml", action="store_true",
        help="Generate the ser2net YAML from the TOML only, then exit "
             "(used as ExecStartPre in the systemd unit)")
    args = parser.parse_args()

    if not Path(args.config).exists():
        print(f"ERROR: Configuration file not found: {args.config}",
              file=sys.stderr)
        sys.exit(1)

    if args.generate_yaml:
        # ExecStartPre mode: exit code determines whether ExecStart runs
        sys.exit(cmd_generate_yaml(args.config))

    # Normal start as ExecStart
    manager = GNSSStackManager(args.config)
    signal.signal(signal.SIGTERM, lambda s, f: _handle_signal(manager, s, f))
    signal.signal(signal.SIGINT,  lambda s, f: _handle_signal(manager, s, f))
    manager.start()


if __name__ == "__main__":
    main()
